id: P004547
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-17 11:41:06.790474
source_metadata:
  id: bdr:W3CN5060
  title: ལས་འབྲས་གསང་ལམ།
  author: ''
  volumes:
    f12524e24d034f69a12eaadcd0602f2c:
      image_group_id: I3CN5062
      title: ''
      volume_number: 1
      total_pages: 157
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
