id: IE6084EC4
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T17:59:07+00:00'
last_modified: '2022-06-08T01:51:11.852897+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN5060
  title: ལས་འབྲས་གསང་ལམ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    47A6:
      image_group_id: I3CN5062
      title: ''
      total_pages: 157
      order: 1
      base_file: 47A6.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
